name: hacksprint_flutter
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  date_format: ^2.0.7
  dio: ^5.4.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  eventflux: ^1.6.6
  file_picker: ^6.1.1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.6.19
  flutter_svg: ^2.0.10+1
  flutter_tts: ^3.8.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  http: ^1.2.0
  injectable: ^2.3.5
  intl: ^0.19.0
  logger: ^2.1.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.2
  build_runner: ^2.4.8
  objectbox_generator: ^2.5.1

flutter:  
  uses-material-design: true

  assets:
    - asset/
    - dev.env


  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
